// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jfxxtyfuccwmfeyltype.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpmeHh0eWZ1Y2N3bWZleWx0eXBlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjY3NTUsImV4cCI6MjA3MzAwMjc1NX0.K99his38ymmt1VGNldyD69rIPvl0DztMH7gMdQXDmus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});